apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhtml
spec:
  selector:
    matchLabels:
      env: production
  replicas: 1
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - name: dep_html
        image: shubham532/web_server
        ports:
        - containerPort: 80
        volumeMounts:
          - name: web
            mountPath: /var/www/html   
      volumes:
      - name: web
        persistentVolumeClaim:
          claimName: web

